---

- name: BIG-IP(APM)  Data-Group Delete
  hosts: big-ip01.internal
  connection: local
  gather_facts: False
  vars_prompt: 
   - name: "DataGroup_Name"
     prompt: "削除したいDataGroupNameを入力あるいはコピー＆ペーストで貼り付けて下さい。"   

  tasks:
    - name: Delete Data-Group
      bigip_data_group:
       internal: yes
       name: "{{ DataGroup_Name }}"
       state: absent
       password: "{{ bigip_password }}"
       server: "{{ ansible_host }}"
       user: "{{ bigip_username }}"
       validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      register: results
      failed_when: results.changed != True
